build(CI): :construction_worker: Split up jump host ssh check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,15 @@ jobs:
     - name: Test SSH Connection to Jump Host and Final VM
       run: |
         # Check if we can reach the cloud VM via the jump host
-        ssh -vvv -o "ProxyJump=et422@shell1.doc.ic.ac.uk" -i ~/.ssh/id_rsa ubuntu@cloud-vm-41-85 "echo Connection Successful"
+        ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa et422@shell1.doc.ic.ac.uk 'echo "Jump host reachable!"'
+
+        if [ $? -eq 0]; then
+          echo "Jump host connection successful"
+          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -J et422@shell1.doc.ic.ac.uk ubuntu@cloud-vm-41-85 'echo "Final VM reachable!"'
+        else
+          echo "Jump host connection failed"
+          exit 1
+        fi
   
     - name: Install dependencies
       run: |
@@ -51,10 +59,10 @@ jobs:
     - name: Copy files to server
       run: |
         # Ensure we're copying files via the jump host to the final VM
-        scp -o "ProxyJump=et422@shell1.doc.ic.ac.uk" -i ~/.ssh/id_rsa -r ./ ubuntu@cloud-vm-41-85:/usr/code
+        scp -J et422@shell1.doc.ic.ac.uk -i ~/.ssh/id_rsa -r ./ ubuntu@cloud-vm-41-85:/usr/code
 
     - name: Restart API service
       run: |
         # SSH via jump host to restart the Flask app service on the cloud VM
-        ssh -o "ProxyJump=et422@shell1.doc.ic.ac.uk" -i ~/.ssh/id_rsa ubuntu@cloud-vm-41-85 'sudo systemctl restart flask_app.service'
+        ssh -J et422@shell1.doc.ic.ac.uk -i ~/.ssh/id_rsa ubuntu@cloud-vm-41-85 'sudo systemctl restart flask_app.service'
 
